plugins {
    id 'com.android.application'
}

android {
    namespace 'com.evchargecalculator'
    compileSdk 36

    defaultConfig {
        applicationId 'com.evcalculator'
        minSdk 23
        targetSdk 36
        versionCode 49
        versionName '1.0.1'
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
