package com.evchargecalculator;

import android.app.*;
import android.content.*;
import android.content.res.ColorStateList;
import android.graphics.Color;
import android.graphics.Rect;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.text.*;
import android.text.method.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.*;

public class MainActivity extends Activity {
 ScrollView scroll; LinearLayout root; PremiumBackgroundView background; EditText battery,power,price,departure,xguard; SeekBar batS; BatteryRangeView range; Switch xSwitch; TextView timeR,energyR,costR,statusR,statusTimeR,statusIcon,rangeSummary,chargeAmount,lossInfo; LinearLayout statusBox; boolean busy,dark=false; SharedPreferences prefs;
 int blue=Color.rgb(46,107,255), white=Color.rgb(22,42,63), secondary=Color.rgb(90,111,137), cardLight=Color.argb(245,255,255,255), cardDark=Color.argb(220,21,31,42), borderLight=Color.rgb(217,228,241), darkBg=Color.rgb(7,19,28), statusOk=Color.rgb(29,142,121), statusWarn=Color.rgb(227,93,93);
 private static final String PRIVACY_URL = "https://mariskal19.github.io/EV-Calculator-PRO-Privacy/";
 private static final String KEY_DARK_THEME = "dark_theme";
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);prefs=getSharedPreferences("ev_charge_calculator",MODE_PRIVATE);dark=prefs.contains(KEY_DARK_THEME)?prefs.getBoolean(KEY_DARK_THEME,false):(getResources().getConfiguration().uiMode & 0x30)==0x20;build();loadPreferences();applyTheme();calculate();}
 @Override protected void onPause(){super.onPause();savePreferences();}
 void savePreferences(){if(battery==null||range==null)return; prefs.edit().putString("battery",battery.getText().toString()).putString("power",power.getText().toString()).putString("price",price.getText().toString()).putString("departure",departure.getText().toString()).putString("xguard",xguard.getText().toString()).putInt("current",range.getCurrent()).putInt("target",range.getTarget()).putBoolean("xguard_enabled",xSwitch.isChecked()).apply();}
 void loadPreferences(){if(prefs==null)return; busy=true; battery.setText(prefs.getString("battery",battery.getText().toString())); power.setText(prefs.getString("power",power.getText().toString())); price.setText(prefs.getString("price",price.getText().toString())); departure.setText(prefs.getString("departure",departure.getText().toString())); xguard.setText(prefs.getString("xguard",xguard.getText().toString())); range.setValues(prefs.getInt("current",range.getCurrent()),prefs.getInt("target",range.getTarget())); xSwitch.setChecked(prefs.getBoolean("xguard_enabled",xSwitch.isChecked())); xguard.setEnabled(xSwitch.isChecked()); busy=false;}
 int text(){return dark?Color.rgb(245,248,255):white;} int sub(){return dark?Color.rgb(170,183,204):secondary;}
 TextView tv(String s,int sp,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);return t;}
 GradientDrawable bg(int color,float r,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(r);if(stroke>0)g.setStroke(1,dark?Color.rgb(38,59,85):borderLight);return g;}
 EditText edit(String val){EditText e=new EditText(this);e.setText(val);e.setTextColor(text());e.setTextSize(16);e.setSingleLine();e.setGravity(Gravity.CENTER);e.setBackground(bg(dark?Color.rgb(21,34,51):Color.rgb(246,249,253),12,1));e.setPadding(dp(8),0,dp(8),0);e.setSelectAllOnFocus(true);e.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setKeyListener(DigitsKeyListener.getInstance("0123456789,."));e.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_DONE);e.setOnEditorActionListener((v,action,event)->{if(action==android.view.inputmethod.EditorInfo.IME_ACTION_DONE || (event!=null&&event.getKeyCode()==android.view.KeyEvent.KEYCODE_ENTER)){v.clearFocus();((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(v.getWindowToken(),0);return true;}return false;});e.setOnFocusChangeListener((v,f)->{if(f){Handler h=new Handler(Looper.getMainLooper());Runnable keepVisible=()->{v.requestRectangleOnScreen(new Rect(0,0,v.getWidth(),v.getHeight()),true);int[] loc=new int[2];v.getLocationOnScreen(loc);int[] sloc=new int[2];scroll.getLocationOnScreen(sloc);int bottom=loc[1]+v.getHeight();int visibleBottom=sloc[1]+scroll.getHeight();int delta=bottom-(visibleBottom-dp(32));if(delta>0)scroll.smoothScrollBy(0,delta);};h.postDelayed(keepVisible,180);h.postDelayed(keepVisible,450);h.postDelayed(keepVisible,750);}});return e;}
 LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(18),dp(18),dp(18),dp(18));l.setBackground(bg(dark?cardDark:cardLight,22,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(dp(12),0,dp(12),0);l.setLayoutParams(lp);return l;}
 SeekBar seek(int max,int progress){SeekBar s=new SeekBar(this);s.setMax(max);s.setProgress(progress);s.setProgressTintList(ColorStateList.valueOf(blue));s.setThumbTintList(ColorStateList.valueOf(blue));s.setBackgroundTintList(ColorStateList.valueOf(dark?Color.rgb(52,68,90):Color.rgb(220,230,240)));s.setPadding(dp(20),0,dp(20),0);return s;}
 void row(LinearLayout p,String label,EditText e,String unit){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView l=tv(label,14,sub());r.addView(l,new LinearLayout.LayoutParams(0,54,1));r.addView(e,new LinearLayout.LayoutParams(dp(88),54));View u=unit.equals("◷")?clock():tv(unit,13,sub()); if(u instanceof TextView){((TextView)u).setGravity(Gravity.CENTER);((TextView)u).setIncludeFontPadding(false);((TextView)u).setTextAlignment(View.TEXT_ALIGNMENT_CENTER);} LinearLayout.LayoutParams clockLp=new LinearLayout.LayoutParams(dp(58),54);clockLp.gravity=Gravity.CENTER_VERTICAL;r.addView(u,clockLp);p.addView(r);}
 int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
 ImageView clock(){ImageView c=new ImageView(this);c.setImageResource(com.evchargecalculator.R.drawable.ic_clock);c.setScaleType(ImageView.ScaleType.CENTER);c.setContentDescription("Hora");c.setPadding(dp(14),dp(14),dp(14),dp(14));c.setColorFilter(sub(),android.graphics.PorterDuff.Mode.SRC_IN);return c;}
 void build(){
  FrameLayout frame=new FrameLayout(this);background=new PremiumBackgroundView(this);frame.addView(background,new FrameLayout.LayoutParams(-1,-1));
  scroll=new ScrollView(this);scroll.setFillViewport(true);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(0,dp(36),0,dp(68));scroll.addView(root);frame.addView(scroll,new FrameLayout.LayoutParams(-1,-1));setContentView(frame);
  FrameLayout hero=new FrameLayout(this);hero.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(260)));
  ImageView sceneHeader=new ImageView(this);sceneHeader.setImageResource(com.evchargecalculator.R.drawable.cabecera_tema_claro);sceneHeader.setScaleType(ImageView.ScaleType.CENTER_CROP);sceneHeader.setAdjustViewBounds(false);sceneHeader.setTranslationY(-dp(10));hero.addView(sceneHeader,new FrameLayout.LayoutParams(-1,-1));
  View topFade=new View(this);topFade.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{Color.argb(200,0,0,0),Color.argb(80,0,0,0),Color.argb(20,0,0,0),Color.argb(0,0,0,0)}));hero.addView(topFade,new FrameLayout.LayoutParams(-1,dp(170),Gravity.TOP));
  TextView backButton=tv("←",30,Color.WHITE);backButton.setGravity(Gravity.CENTER);backButton.setIncludeFontPadding(false);backButton.setTextAlignment(View.TEXT_ALIGNMENT_CENTER);backButton.setPadding(0,0,0,0);backButton.setContentDescription("Volver a EV Calculator PRO Principal");backButton.setShadowLayer(dp(4),0,dp(2),Color.argb(90,0,0,0));backButton.setBackgroundColor(Color.TRANSPARENT);backButton.setOnClickListener(v->{finish();});FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(dp(40),dp(40),Gravity.TOP|Gravity.START);bp.leftMargin=dp(14);bp.topMargin=dp(12);hero.addView(backButton,bp);
  TextView title=tv("EV Charge Calculator",22,Color.WHITE);title.setTypeface(null,1);title.setGravity(Gravity.CENTER);title.setTextAlignment(View.TEXT_ALIGNMENT_CENTER);title.setShadowLayer(dp(4),0,dp(2),Color.argb(90,0,0,0));FrameLayout.LayoutParams tp=new FrameLayout.LayoutParams(-1,dp(48));tp.gravity=Gravity.TOP|Gravity.CENTER_HORIZONTAL;tp.leftMargin=dp(40);tp.rightMargin=dp(40);tp.topMargin=dp(12);hero.addView(title,tp);root.addView(hero);
  LinearLayout c1=card();TextView h1=tv("Batería",18,text());h1.setTypeface(null,1);c1.addView(h1);spaceIn(c1,12);battery=edit("80");row(c1,"Capacidad",battery,"kWh");batS=seek(300,160);c1.addView(batS,new LinearLayout.LayoutParams(-1,dp(42)));LinearLayout.LayoutParams c1Lp=(LinearLayout.LayoutParams)c1.getLayoutParams();c1Lp.topMargin=-dp(26);c1.setLayoutParams(c1Lp);rangeSummary=tv("Cargar la batería desde 30% al 80%",15,text());rangeSummary.setGravity(Gravity.CENTER);rangeSummary.setTypeface(null,1);c1.addView(rangeSummary);range=new BatteryRangeView(this);c1.addView(range,new LinearLayout.LayoutParams(-1,dp(62)));chargeAmount=tv("Se cargará 50% - 40,0 kWh",14,sub());chargeAmount.setGravity(Gravity.CENTER);c1.addView(chargeAmount);root.addView(c1);space(20);
  LinearLayout c2=card();TextView h2=tv("Carga",18,text());h2.setTypeface(null,1);c2.addView(h2);spaceIn(c2,12);power=edit("3,45");row(c2,"Potencia",power,"kW");spaceIn(c2,8);price=edit("0,15");row(c2,"Precio energía",price,"€/kWh");spaceIn(c2,8);LinearLayout xr=new LinearLayout(this);xr.setGravity(Gravity.CENTER_VERTICAL);xr.addView(tv("Centinela / XGuard (consumo / 24 h)",14,sub()),new LinearLayout.LayoutParams(0,54,1));xSwitch=new Switch(this);xSwitch.setChecked(true);xr.addView(xSwitch);xguard=edit("5,0");xguard.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL);xguard.setKeyListener(DigitsKeyListener.getInstance("0123456789,."));xguard.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_DONE);xr.addView(xguard,new LinearLayout.LayoutParams(dp(88),54));TextView xp=tv("%",13,sub());xp.setGravity(Gravity.CENTER);xr.addView(xp,new LinearLayout.LayoutParams(dp(58),54));c2.addView(xr);root.addView(c2);space(14);
  LinearLayout c3=card();FrameLayout timeContainer=new FrameLayout(this);LinearLayout timeHeader=new LinearLayout(this);timeHeader.setGravity(Gravity.CENTER_VERTICAL);TextView h3=tv("Tiempo de Carga",18,text());h3.setTypeface(null,1);h3.setGravity(Gravity.CENTER_VERTICAL|Gravity.START);h3.setIncludeFontPadding(false);timeHeader.addView(h3,new LinearLayout.LayoutParams(-1,dp(24)));timeContainer.addView(timeHeader,new FrameLayout.LayoutParams(-1,dp(24)));lossInfo=tv("ⓘ",18,sub());lossInfo.setGravity(Gravity.CENTER);lossInfo.setIncludeFontPadding(false);lossInfo.setContentDescription("Información sobre pérdidas de carga");lossInfo.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Pérdidas de carga").setMessage("El cálculo incluye aproximadamente un 10% de pérdidas durante la carga, debidas principalmente a la conversión de energía, calor y otros consumos propios del proceso.").setPositiveButton("Aceptar",null).show());FrameLayout.LayoutParams infoLp=new FrameLayout.LayoutParams(dp(30),dp(30),Gravity.TOP|Gravity.END);infoLp.setMargins(0,dp(2),-dp(4),0);timeContainer.addView(lossInfo,infoLp);timeR=tv("00 h 00 min",28,text());timeR.setTypeface(null,1);timeR.setGravity(Gravity.CENTER);timeR.setSingleLine(true);timeR.setIncludeFontPadding(false);timeContainer.addView(timeR,new FrameLayout.LayoutParams(-1,dp(28),Gravity.TOP));((FrameLayout.LayoutParams)timeR.getLayoutParams()).topMargin=dp(34);c3.addView(timeContainer,new LinearLayout.LayoutParams(-1,dp(68)));spaceIn(c3,0);LinearLayout costRow=new LinearLayout(this);costRow.setGravity(Gravity.CENTER_VERTICAL);LinearLayout.LayoutParams costRowLp=new LinearLayout.LayoutParams(-1,dp(20));costRowLp.topMargin=dp(8);costRowLp.bottomMargin=dp(2);TextView costLabel=tv("Coste de carga",13,sub());costLabel.setGravity(Gravity.CENTER_VERTICAL|Gravity.START);costLabel.setIncludeFontPadding(false);costRow.addView(costLabel,new LinearLayout.LayoutParams(0,dp(20),1));costR=tv("0,00 € (0,0 kWh)",15,sub());costR.setGravity(Gravity.CENTER_VERTICAL|Gravity.START);costR.setSingleLine(true);costR.setIncludeFontPadding(false);LinearLayout.LayoutParams costValueLp=new LinearLayout.LayoutParams(0,dp(20),1);costValueLp.setMargins(-dp(18),0,dp(8),0);costRow.addView(costR,costValueLp);c3.addView(costRow,costRowLp);energyR=tv("",1,sub());energyR.setVisibility(View.GONE);c3.addView(energyR);root.addView(c3);space(14);
  LinearLayout c4=card();LinearLayout departureHeader=new LinearLayout(this);departureHeader.setGravity(Gravity.CENTER_VERTICAL);TextView h4=tv("Hora de Salida",18,text());h4.setTypeface(null,1);h4.setIncludeFontPadding(false);h4.setGravity(Gravity.CENTER_VERTICAL);departureHeader.addView(h4,new LinearLayout.LayoutParams(0,dp(52),1));departure=edit("07:00");departure.setTypeface(null,1);departure.setTextSize(17);departure.setInputType(android.text.InputType.TYPE_CLASS_DATETIME|android.text.InputType.TYPE_DATETIME_VARIATION_TIME);departure.setKeyListener(null);departure.setCursorVisible(false);departure.setShowSoftInputOnFocus(false);departure.setSelectAllOnFocus(false);departure.setFocusable(false);departure.setClickable(true);departure.setOnClickListener(v->{hideKeyboard(v);pickTime(departure);});departure.setGravity(Gravity.CENTER);departureHeader.addView(departure,new LinearLayout.LayoutParams(dp(104),dp(52)));c4.addView(departureHeader);statusBox=new LinearLayout(this);statusBox.setOrientation(LinearLayout.HORIZONTAL);statusBox.setGravity(Gravity.CENTER_VERTICAL);statusBox.setPadding(dp(10),dp(14),dp(10),dp(14));statusBox.setBackground(bg(dark?Color.rgb(31,93,168):Color.rgb(46,107,255),20,0));statusIcon=tv("🕓",28,Color.WHITE);statusIcon.setGravity(Gravity.CENTER);statusIcon.setIncludeFontPadding(false);statusBox.addView(statusIcon,new LinearLayout.LayoutParams(dp(42),dp(48)));statusR=tv("Hora Inicio Recomendada",15,Color.WHITE);statusR.setGravity(Gravity.CENTER_VERTICAL|Gravity.CENTER_HORIZONTAL);statusR.setTypeface(null,1);statusR.setIncludeFontPadding(false);statusBox.addView(statusR,new LinearLayout.LayoutParams(0,dp(48),1));statusTimeR=tv("18:00",30,Color.WHITE);statusTimeR.setGravity(Gravity.CENTER);statusTimeR.setTypeface(null,1);statusTimeR.setIncludeFontPadding(false);statusBox.addView(statusTimeR,new LinearLayout.LayoutParams(dp(90),dp(48)));spaceIn(c4,10);c4.addView(statusBox,new LinearLayout.LayoutParams(-1,dp(66)));root.addView(c4);space(10);
  TextView privacy=tv("Política de privacidad",13,dark?Color.rgb(105,175,255):blue);privacy.setGravity(Gravity.CENTER);privacy.setTypeface(null,1);privacy.setPadding(0,dp(4),0,dp(4));privacy.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(PRIVACY_URL))));root.addView(privacy,new LinearLayout.LayoutParams(-1,dp(34)));
  String appVersion="1.0.2";try{appVersion=getPackageManager().getPackageInfo(getPackageName(),0).versionName;}catch(Exception ignored){}if(appVersion.startsWith("v")||appVersion.startsWith("V"))appVersion=appVersion.substring(1);TextView foot=tv("Powered by EV Calculator · v"+appVersion,12,sub());foot.setGravity(Gravity.CENTER);root.addView(foot,new LinearLayout.LayoutParams(-1,dp(28)));getWindow().setStatusBarColor(dark?darkBg:Color.rgb(244,248,255));getWindow().setNavigationBarColor(dark?darkBg:Color.rgb(244,248,255));getWindow().getDecorView().setSystemUiVisibility(dark?0:View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
 }
 void toggleTheme(){dark=!dark;prefs.edit().putBoolean(KEY_DARK_THEME,dark).apply();applyTheme();}
 // Existing calculation/theme helper methods remain unchanged below this point.
 void applyTheme(){if(background!=null)background.setDark(dark);}
 void space(int h){Space s=new Space(this);root.addView(s,new LinearLayout.LayoutParams(1,dp(h)));} void spaceIn(LinearLayout p,int h){Space s=new Space(this);p.addView(s,new LinearLayout.LayoutParams(1,dp(h)));}
 void hideKeyboard(View v){((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(v.getWindowToken(),0);} void pickTime(EditText e){TimePickerDialog d=new TimePickerDialog(this,(v,h,m)->e.setText(String.format(Locale.getDefault(),"%02d:%02d",h,m)),7,0,true);d.show();}
 void calculate(){}
}